import { getUserSession } from "@/actions/session/session.action";
import Aside from "@/components/layout/aside/aside";
import Header from "@/components/layout/header/header";
import { ThemeProvider } from "@/provider/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import { grotesk, lato, roboto } from "./fonts/fonts";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Paku architecture",
  description: "Generated by taypedev",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserSession();
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${lato.variable} ${grotesk.variable} flex relative overflow-hidden font-lato`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <SessionProvider>
            <Aside user={user} />
            <main className="w-full flex-1 overflow-hidden h-screen overflow-y-auto relative bg-secondary">
              <Header user={user} />
              {children}
            </main>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
